### ISSUE TITLE
Possible thread-safety issue in GetExpirationForCacheRegion

### ISSUE THREAD

**Issue by DominicCronin** [dd4t/DD4T.Core#91] opened 2016-06-08 09:15 UTC
In debug sessions, I've seen occasional exceptions apparently caused by trying to add a duplicate key to the dictionary in GetExpirationForCacheRegion

https://github.com/dd4t/DD4T.Core/blob/develop/source/DD4T.Utils/DD4TConfiguration.cs#L442

I'm guessing this happens because of a thread-switch between the if and the Add. 

Bonus: The logic is not really clear in this routine. It should only do the string.Format once, and there should be a comment explaining why we test the string version and then use the int.

**Comment by chrismrgn** [comment] 2016-06-08 10:19
Should possibly be replaced with ConcurrentDictionary<TKey, TValue>?

**Comment by albertromkes** [comment] 2016-07-17 19:46
Related to issue #62

**Comment by quirijnslings** [comment] 2016-10-07 17:30
The issue is fixed. You need to upgrade to the latest prerelease package of the DD4T.Core.

**Comment by avmgan** [comment] 2017-03-04 06:11
I can see this issue has been fixed, but not merged with the latest version on 2.1.0, we still get this issue on the latest version on 2.1.0, it leads High CPU some time because of possible thread-safety issue in GetExpirationForCacheRegion.

10:03:20.09  Error    GlobalExceptionHandler.Handle - Request Url: http://webapi.xxxx.ae/getnews/en/202155
             ...      System.ArgumentException (mscorlib)
             ...      An item with the same key has already been added.
             ...         at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
             ...         at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
             **...         at DD4T.Utils.DD4TConfiguration.GetExpirationForCacheRegion(String region)**
             ...         at DD4T.Utils.Caching.DefaultCacheAgent.FindCacheItemPolicy(String key, Object item, String region)
             ...         at DD4T.Utils.Caching.DefaultCacheAgent.Store(String key, String region, Object item, List`1 dependOnTcmUris)
             ...         at DD4T.Utils.Caching.DefaultCacheAgent.Store(String key, String region, Object item)
             ...         at DD4T.Factories.PageFactory.TryFindPageContent(String url, String& pageContent)
             ...         at Indivirtual.DD4T.Tridion.Misc.Utilities.GetDynamicXML(String fileName)
             ...         at Indivirtual.DD4T.Tridion.Misc.SiteData..ctor(String publicationUrl)
             ...         at Indivirtual.Sharjah24.Api.Filters.PublicationDependentAttribute.OnActionExecuting(HttpActionContext actionContext)
             ...         at System.Web.Http.Filters.ActionFilterAttribute.OnActionExecutingAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
             ...      --- End of stack trace from previous location where exception was thrown ---
             ...         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
             ...         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             ...         at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
             ...      --- End of stack trace from previous location where exception was thrown ---
             ...         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
             ...         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             ...         at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
             ...      --- End of stack trace from previous location where exception was thrown ---
             ...         at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
             ...      --- End of stack trace from previous location where exception was thrown ---
             ...         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
             ...         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             ...         at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
             ...      --- End of stack trace from previous location where exception was thrown ---
             ...         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
             ...         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             ...         at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
             ...      --- End of stack trace from previous location where exception was thrown ---
             ...         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
             ...         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             ...         at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
             ...      --- End of stack trace from previous location where exception was thrown ---
             ...         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
             ...         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             ...         at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__0.MoveNext()
             ...      --- End of stack trace from previous location where exception was thrown ---
             ...         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
             ...         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             ...         at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
             ...      
10:03:21.65  Error    {0}: Could not execute query
             ...      System.ArgumentException (mscorlib)
             ...      An item with the same key has already been added.
             ...         at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
             ...         at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
             **...         at DD4T.Utils.DD4TConfiguration.GetExpirationForCacheRegion(String region)**
             ...         at DD4T.Utils.Caching.DefaultCacheAgent.FindCacheItemPolicy(String key, Object item, String region)
             ...         at DD4T.Utils.Caching.DefaultCacheAgent.Store(String key, String region, Object item, List`1 dependOnTcmUris)
             ...         at DD4T.Factories.ComponentPresentationFactory.TryGetComponentPresentation(IComponentPresentation& cp, String componentUri, String templateUri)
             ...         at DD4T.Factories.ComponentFactory.TryGetComponent(String componentUri, IComponent& component, String templateUri)
             ...         at Indivirtual.DD4T.Tridion.Broker.BrokerQuery.<>c.<Execute>b__17_0(String c)
             ...         at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
             ...         at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
             ...         at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
             ...         at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
             ...         at Indivirtual.DD4T.Tridion.Broker.BrokerQuery.Execute(Int32 pageIndex, Int32 pageSize, Int32 initialTake)
             ... 

Could you please merge this fix with latest version and adivse?

**Comment by maheshthakur1529** [comment] 2017-06-19 10:26
Hi Team,

We are also facing this same issue when the load on the application is high. It is choking the web server CPU and we have restart the iis to solve that . Can you please let us know when and in which relaease this issue was resolved as we are using the latest dlls of DD4t 2.1.0.0 . Please advise ?

**Comment by quirijnslings** [comment] 2017-06-19 11:06
You need to upgrade to 2.2 to fix this.

**Comment by kpmrafeeq** [comment] 2017-06-19 12:04
I have upgraded to Web8.5 with DD4T 2.2 and I do not see this issue from past 3 weeks.

**Closed** 2019-12-12 14:35 UTC
Labels: bug, fixed
